defaults:
  - schema_tune

params:
  use_time2vec:
    - True
    - False
  use_value2vec:
    - True
    - False
  lstm_num_layers:
    - 2
    - 4
    - 8
  lstm_hidden_state:
    - 128
    - 256
    - 512
    - 1024
  regressor_head_dims:
    -
      - 32
    -
      - 64
      - 32
    -
      - 128
      - 128
      - 64
    -
      - 64
      - 128
      - 32