defaults:
  - schema_tune

params:
  nbeats_num_blocks:
    -
      - 8
      - 8
    -
      - 4
      - 4
  nbeats_num_layers:
    -
      - 4
      - 4
    -
      - 8
      - 8
  nbeats_num_hidden:
    - 32
    - 64
    - 128
    - 256
  nbeats_exogenous_n_channels:
    - 16
    - 32
  use_time2vec:
    - True
    - False
