defaults:
  - schema_tune

params:
  arima_p:
    - 0
    - 1
    - 2
    - 3
  arima_q:
    - 0
    - 1
    - 2
    - 3
  sarima_P:
    - 0
    - 1
    - 2
    - 3
  sarima_Q:
    - 0
    - 1
    - 2
    - 3