defaults:
  - schema_tune

params:
  use_time2vec:
    - True
    - False
  use_value2vec:
    - True
    - False
  transformer_ff_dim:
    - 128
    - 256
    - 512
  transformer_encoder_layers:
    - 2
    - 4
    - 6
    - 8
  use_pos_encoding:
    - True
    - False
