defaults:
  - schema_tune

params:
  use_time2vec:
    - True
    - False
  use_value2vec:
    - True
    - False
  teacher_forcing_epoch_num:
    - 0
    - 20
    - 40
    - 80
  transformer_ff_dim:
    - 128
    - 256
    - 512
  transformer_encoder_layers:
    - 2
    - 4
    - 6
  transformer_decoder_layers:
    - 2
    - 4
    - 6
  classification_head_dims:
    -
      - 32
    -
      - 64
      - 32
    -
      - 128
      - 128
      - 64
    -
      - 64
      - 128
      - 32
