defaults:
  - schema_tune

params:
  use_time2vec:
    - True
    - False
  use_value2vec:
    - True
    - False
  transformer_ff_dim:
    - 128
    - 256
    - 512
  transformer_encoder_layers:
    - 2
    - 4
    - 6
  use_pos_encoding:
    - True
    - False
  regressor_head_dims:
    -
      - 32
    -
      - 64
      - 32
    -
      - 128
      - 128
      - 64
    -
      - 64
      - 128
      - 32
