# Specific experiments settings
# (default settings inherited from configs.experiment.ExperimentSettings)

defaults:
  - schema_experiment

_tags_:
  - DENSE_GFS

resume_checkpoint: ~

datamodule:
  _target_: wind_forecast.datamodules.SingleGFSPointDataModule.SingleGFSPointDataModule

model:
  _target_: wind_forecast.models.DenseModel.DenseModel

system:
  _target_: wind_forecast.systems.Regressor.Regressor

sequence_length: 1